spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/springboot
#    username: postgresql
#    password: postgrespassword
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true

logging.level:
  org.hibernate.SQL: debug
